#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sh $HOME/Scripts/startup.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 
bspc config right_padding 00
bspc config bottom_padding 00
bspc config left_padding 00
bspc config border_with 0
bspc config window_gap 12
