# set variables

# change zsh options

# aliases
## general
alias cls='clear'
alias ls='ls -lh --color=auto'
alias lsa='ls -lAFh --color=auto'
alias vim='nvim'
alias srccfg='source $HOME/.zshrc'
alias 'cd..'='cd ..'
alias mkdir='mkdir -p'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias grub-mkconfig='grub-make-config'
alias btctl='bluetoothctl'
alias screenshot='$HOME/Scripts/media/screenshot.sh'

## git
alias gic='git commit -m'
alias gica='git commit -am'
alias gip='git push'
alias gia='git add .'
alias gid='git diff'
alias gis='git status'

# customize prompt(s)
PROMPT='%1~ %# '
RPROMPT='%*'

# add location to $PATH

# functions
function mkcd() {
    command mkdir -p "$@" &&
    cd "$_"
}

function grub-make-config() {
    mkdir -p /mnt-win &&
    mount /dev/nvme0n1p1 /mnt-win &&
    command grub-mkconfig -o /boot/grub/grub.cfg
}

function keycode() {
    xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
}

function screenshots() {
	cd "$HOME/Pictures/screenshots" &&
	lsa
}

# plugins

# other
