# set variables

# change zsh options

# set aliases
alias cls='clear'
alias ls='ls -lh --color=auto'
alias lsa='ls -lAFh --color=auto'
alias vim='nvim'
alias srccfg='source $HOME/.zshrc'
alias 'cd..'='cd ..'
alias mkdir='mkdir -p'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias grub-mkconfig='grub-make-config'
alias btctl='bluetoothctl'

# customize prompt(s)
PROMPT='%1~ %# '
RPROMPT='%*'

# add location to $PATH

# functions
function mkcd() {
	command mkdir -p $@ &&
	cd $_
}

function grub-make-config() {
	mkdir -p /mnt-win &&
	mount /dev/nvme0n1p1 /mnt-win &&
	command grub-mkconfig -o /boot/grub/grub.cfg
}

# plugins

# other
